version: "3"

services:
  # Postgres DB
  local-db:
    container_name: local-dashboard-db
    image: postgres:bullseye
    restart: always
    networks:
      - local-dashboard-tier
    env_file:
      - ./dashboard-server/.env
    ports:
      - "5432:5432"

networks:
  local-dashboard-tier:
    driver: bridge